Repository mansona/lint-to-the-future-stylelint, pull requests merged in 2025-03, with the labels that each got.

#10 drop support for node 14 and 16
  .github/workflows/tests.yaml
Labels: breaking

#12 start using release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .release-it.js
  CHANGELOG.md
  RELEASE.md
  changelog.template
  package.json
  pnpm-lock.yaml
Labels: internal

#14 convert to vitest
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  test/ignore.test.mjs
  test/list.test.mjs
Labels: internal

#15 add an end-to-end test
  package.json
  pnpm-lock.yaml
  test/end-to-end.test.js
Labels: internal

#16 swap to esm only and drop esm dependency
  .eslintrc.json
  eslint.config.js
  index.js
  package.json
  pnpm-lock.yaml
  test/ignore.test.js
  test/list.test.js
Labels: breaking

#9 Improve ignore handling
  main.mjs
Labels: enhancement

#17 Switch to globby for better ignoring
  main.mjs
  package.json
  pnpm-lock.yaml
Labels: enhancement
